### ISSUE TITLE
Error while running plot_ground_metric.py

### ISSUE THREAD

**Issue by anujanegi** [AliHashemi-ai/eeg#1]
Follwing runtime error is raised in this line -
`brain = stc0.plot(subject, hemi="both", subjects_dir=subjects_dir)`

**Error -** 
Using control points [0. 0. 0.] plot_ground_metric.py:33: 
RuntimeWarning: All data were zero brain = stc0.plot(subject, hemi="both", subjects_dir=subjects_dir) 
Segmentation fault (core dumped)

@agramfort @AliHashemi-ai

**Comment by agramfort** [comment]
what does

mne.sys_info()

print?

>

**Comment by anujanegi** [comment]
```
>>> mne.sys_info()
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.
```

**Comment by agramfort** [comment]
ok so you are on a server with no 3D display. It's a headless server

see
https://mne.tools/stable/install/advanced.html#off-screen-rendering-with-mesa
https://mne.tools/stable/install/mne_python.html?highlight=server%20environment#installing-to-a-headless-server

tell me if it helps

>

**Comment by anujanegi** [comment]
Thanks! Was able to fix this. The script runs now and plots, but gives a runtime warning in the process - 
```
/home/anujanegi/tj/bdsg/eeg/plot_ground_metric.py:33: RuntimeWarning: All data were zero
  brain = stc0.plot(subject, hemi="both", subjects_dir=subjects_dir)
```
What does this mean? Do you think this is an issue?
