### ISSUE TITLE
Issue in display_true_pred_parcels() in source_localisation.py

### ISSUE THREAD

**Issue by anujanegi** [AliHashemi-ai/eeg#4]
![image](https://user-images.githubusercontent.com/29161453/123501587-4a726d80-d646-11eb-91fc-a4019c853153.png)
![image](https://user-images.githubusercontent.com/29161453/123501627-8f969f80-d646-11eb-9ca2-fbc57062dc5e.png)

The function uses plot_y_pred_true_parcels() from plot_signal.py script to plot all predicted parcels (donated in yellow), ground truth parcels (donated in blue) and overlapping (in green). I get this. 

Can't figure out if the code is faulty or if this is a rendering thing? The code looks right, from as far as I understand.
@AliHashemi-ai @agramfort

**Comment by agramfort** [comment]
can you share the code you used to make this figure. I don't have enough information to debug locally.

**Comment by anujanegi** [comment]
You can run source_localisation.py on the BIDS-version branch.
